### ISSUE TITLE
Question: shares worth 1 euro and worth 50 euros

### ISSUE THREAD

**Issue by Juice10** [vindia/dutch-business-guides#1]
Hi,

I was wondering why the shares where worth €1,- in one screen and €50 in the others?

Keep up the good work, this is great!

Cheers,
Justin

**Comment by vindia** [comment]
Yes. 

* For my personal holding 100 shares of €0,01 each were issued, totalling a value of €1,-. 
* For our main startup B.V. we issued 10.000 shares of €0,01 each, 5.000 for each founder's holding. So the value of that is €50,-.

If this isn't clear anywhere, I can have a look and update it.

**Comment by Juice10** [comment]
Ah thats clear, sorry didn't get that when skimming through it. Thanks!
